name: Test

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    test:
        name: ${{ matrix.os }}/${{ matrix.arch }} Node ${{ matrix.node }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest, macos-latest ]
                node: [ 20, 22, 24 ]
                arch: [ x64, arm64 ]
                exclude:
                    -   os: ubuntu-latest
                        arch: arm64
                    -   os: macos-latest
                        arch: x64
                include:
                    -   os: windows-latest
                        arch: x64
                        node: 22
                    -   os: ubuntu-latest
                        arch: arm64
                        node: 22
                    -   os: macos-latest
                        arch: x64
                        node: 22
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.node }}
            cancel-in-progress: true
        steps:
            -   name: Checkout Repo
                uses: actions/checkout@v4

            -   name: Setup Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: ${{ matrix.node }}

            -   name: Setup pnpm
                uses: pnpm/action-setup@v4

            -   name: Install Dependencies
                run: pnpm install

            -   name: Test
                run: pnpm test

    release:
        name: Trigger Release
        needs:
            - test
        if: github.ref == 'refs/heads/master'
        uses: ./.github/workflows/release.yml
        permissions:
            contents: write
            pull-requests: write
            actions: write
        secrets: inherit
